version: "3.8"

services:
  db:
    image: mysql
    container_name: mysql_db_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rohan123
      MYSQL_DATABASE: mysqlbookdb
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD-SHELL" , "mysqladmin ping -h localhost -uroot -prohan123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build: .
    container_name: springbootimage
    environment:
      MYSQL_HOST : db
      MYSQL_PORT : 3306
      MYSQL_USERNAME : root
      MYSQL_PASSWORD: rohan123
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data: